version: "3.9"

services:
  products:
    build: 
      context: .
      dockerfile: ProductCatalogSvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8086:80"
  cartdb:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "cartapp"
      POSTGRES_PASSWORD: "cartpw"
    volumes:
      - ./ShoppingCartSvc/database-scripts/:/docker-entrypoint-initdb.d
  carts:
    build: 
      context: .
      dockerfile: ShoppingCartSvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:80"
    links:
      - cartdb
      - products
