version: "3.9"

services:
  cart:
    build: 
      context: .
      dockerfile: HelloMicroservices/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:80"
  cartdb:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
