version: "3.9"

services:
  cartdb:
    image: postgres:13
    environment:
      POSTGRES_USER: "cartapp"
      POSTGRES_PASSWORD: "cartpw"
    volumes:
      - ./ShoppingCartSvc/database-scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db
  cartsvc:
    build: 
      context: .
      dockerfile: ShoppingCartSvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:80"
    networks:
      - bus
      - db
  productsvc:
    build: 
      context: .
      dockerfile: ProductCatalogSvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8086:80"
    networks:
      - bus
networks:
  bus:
  db:
